### ISSUE TITLE
doctest fails in julia 0.4 master

### ISSUE THREAD

**Issue by garrison** [JuliaLang/JuliaDoc#13]
`jldoctest.py` [currently relies on an `mstr` macro](https://github.com/JuliaLang/JuliaDoc/blob/15e0f6f97ecd08f93504b639956047968e3e6a42/juliadoc/jldoctest.py#L805), but these were removed in JuliaLang/julia#10228.  At this point, `make doctest` fails for `julia` `master`, as recently discovered [by a post to julia-users](https://groups.google.com/d/msg/julia-users/n0OjsGJpMRc/XOdv7Uqtu9oJ).

**Comment by ivarne** [comment]
Seems to be fixed by @pao in https://github.com/JuliaLang/JuliaDoc/commit/012be05a6a704fbdce09ff5c3f060930d6d427f9
