### ISSUE TITLE
theme directory not installed

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/JuliaDoc#2]
I ran

```
pip install git+git://github.com/JuliaLang/JuliaDoc.git#egg=JuliaDoc
```

Then in python:

```
>>> juliadoc.get_theme_dir()
'/usr/local/lib/python2.7/dist-packages/juliadoc/theme'
```

but the `theme` directory in `/usr/local/lib/python2.7/dist-packages/juliadoc` seems to be missing.

**Comment by rprechelt** [comment]
Any resolution on this issue? It still affects current installations of this package.

**Comment by mgeier** [comment]
I've created #24, which should fix this issue.

**Comment by mgeier** [comment]
Ping?
