### ISSUE TITLE
Isolating doctest blocks

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/JuliaDoc#20]
While looking into https://github.com/JuliaLang/julia/pull/15753 I found that doctests are not run as independently as one would wish. 

```
Here we document the immensely important f function.

.. doctest::
    julia> f() = 3
    f (generic function with 1 method)

A few hundred later we show a different example.

.. doctest::
    julia> f() = 5
    WARNING: Method definition f() in module Main at none:1 overwritten at none:1.
    f (generic function with 1 method)
```

For functions like `f` it is not a big problem to rename them to `f1`. But renaming them adds clutter without adding information and in examples like http://docs.julialang.org/en/latest/manual/stacktraces/ it seems excessive.
Furthermore it means that doctests are coupled, when the should probably be isolated.

To be clear in my opinion the following should be as it is, since it is one doctest block.
```
Here we document the immensely important f function.

.. doctest::
    julia> f() = 3
    f (generic function with 1 method)

    julia> f() = 5
    WARNING: Method definition f() in module Main at none:1 overwritten at none:1.
    f (generic function with 1 method)

```

**Comment by vchuravy** [comment]
The simplest solution might be to run `workspace()` before executing a new doctest block.

**Comment by yuyichao** [comment]
We have doc that uses previously defined value http://julia.readthedocs.org/en/latest/manual/functions/

**Comment by vchuravy** [comment]
right onto renaming methods then.
