### ISSUE TITLE
Explain first use of ÷ in the manual

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaLang/JuliaDoc#25]
In http://docs.julialang.org/en/latest/manual/strings.html it shows this example:
julia> str[end÷2]
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)

But the meaning of the '÷' symbol is not explained. I'm guessing that it is a division operator but then why not use '/' ? So I think some explanation is appropriate.

**Comment by yuyichao** [comment]
The search is pretty bad but it is explained.

http://docs.julialang.org/en/latest/stdlib/math.html#Base.div

**Comment by timholy** [comment]
If one person is willing to go to the effort to report this (which takes more effort than doing nothing), I suspect we should assume that others may be confused, too. On that principle, I'd like to propose that we reopen this.

There's a difference between having a manual that experienced programmers can understand and one that's suitable for a wide audience. I think we've done really well in putting together a great manual. But we're all software developers, and I don't doubt that a first-class "documentation writer" (someone who does this for a living) would see numerous weaknesses in what we have now---something truly professional requires skills that are their own kind of expertise. As we move towards 1.0, I think we need to pay attention to this kind of stuff.

[This](https://www.ibiblio.org/oswg/docs/writers.html) seems interesting, but the mailing list seems dead so it's probably not relevant anymore.

**Comment by simonbyrne** [comment]
Agreed: we should reopen it on the main Julia repo though.

**Comment by yuyichao** [comment]
I agree this is confusing but I closed this because it's basically a dup of https://github.com/JuliaLang/JuliaDoc/issues/26
