### ISSUE TITLE
Suggestion: Examples should only throw custom exceptions

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaLang/JuliaDoc#28]
In http://docs.julialang.org/en/latest/manual/control-flow.html
There is this example:
julia> f(x) = x>=0 ? exp(-x) : throw(DomainError())
f (generic function with 1 method)

In my experience throwing built-in exceptions only makes sense for library writers who are creating classes compatible with standard ones. (For example a custom MyDict that matched the Dict API.)
But for user code it is normally best to throw a custom exception: that way you never mask a built-in exception when catching and clearly know that the problem is in your own implementation rather than in your use of a standard facility.

**Comment by yuyichao** [comment]
At least for this example the builtin exception is the correct one to throw.

**Comment by mark-summerfield** [comment]
Then the example ought to be changed or at least explain that while it makes sense to to throw built-in exceptions for library code, custom exceptions are best for application code (so that built-in and library exceptions don't get accidentally masked).

**Comment by yuyichao** [comment]
The scenario you should use each of the builtin exceptions are described for each exception type, e.g. http://docs.julialang.org/en/latest/stdlib/base.html#Core.DomainError

**Comment by nalimilan** [comment]
But indeed whether people are supposed to use standard exceptions or not would deserve a mention in the manual.
